In [16]:
print("hello")

hello


In [2]:
import numpy as np

In [8]:
arr=np.array([10,20,30,40])

In [9]:
print(arr)

[10 20 30 40]


In [12]:
arr1=np.array([[10,20,30,40],[20,30,40,50]])


In [15]:
print(type(arr1))
print(arr1)

<class 'numpy.ndarray'>
[[10 20 30 40]
 [20 30 40 50]]


In [18]:
print(arr1[1,2:3])
print(arr1[0,2:3])

[40]
[30]


In [19]:
arr2=np.array([[10,20,30,40],[20,30,40,50],[40,50,60,70]])

In [20]:
print(np.shape(arr2))

(3, 4)


In [24]:
print(np.size(arr2))
print(np.ndim(arr2))
print(arr.dtype)


12
2
int64


In [25]:
a=[12,14,121,41,23,13]
arr=np.array(a)
print(arr)

[ 12  14 121  41  23  13]


In [29]:
arr1=np.array([10,20,30,40])
arr2=np.array([30,50,30,60])
print(arr1+arr2)
print(arr1-arr2)+
print(arr1*arr2)
print(arr1/arr2)

[ 40  70  60 100]
[-20 -30   0 -20]
[ 300 1000  900 2400]
[0.33333333 0.4        1.         0.66666667]


In [31]:
print(np.concatenate([arr1,arr2]))

[10 20 30 40 30 50 30 60]


In [34]:
arr1=np.array([[10,20,30,40],[30,50,40,70]])
print(arr1)
b=np.array_split(arr1,3)
print(b)


[[10 20 30 40]
 [30 50 40 70]]
[array([[10, 20, 30, 40]]), array([[30, 50, 40, 70]]), array([], shape=(0, 4), dtype=int64)]


In [35]:
print(np.append(arr1,[34,100]))

[ 10  20  30  40  30  50  40  70  34 100]
